### ISSUE TITLE
Issue with design decisions

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx_rtd_theme#1017]
Just a couple of compliments, then some complains, bear with me 😅.

First, thank you. The ReadTheDocs project is awesome and fantastic! It's greatly improved the state of my documentation teams documentation. The web hosting is very generous, and the Sphinx theme is fabulous.

Now on to the complains... Is it going to be another 5-9 months before things get reviewed again? I assumed that #234 being solved would cause this project to gain momentum, but besides one instance, it just died again with no PR reviews and issues just constantly being marked as "Design Decision". Speaking of which, based on the amount this is put in, it seems like it's just a catch-all for a bunch of issues.

Are "Design Decisions" ever going to be made, or only once every 2 years? (A little bit of an exaggeration)

...

Just trying to get some momentum back in this project again, I love you guys and what you do, and I'm assuming it's an incredibly small team. I just wonder what the stance is on things, before I fork and merge a couple pending PRs myself for my organizations use. In particular, #986 is very very important to us

**Comment by stsewd** [comment]
Hi, I just reviewed and replied to most issues a couple of weeks ago https://github.com/readthedocs/sphinx_rtd_theme/issues/997. And, yes the main cause is because we are a small team (5) managing several projects, and the team that's familiar with the theme is working in the re-design of the readthedocs.org site, so reviews here and decisions will be a little slow till that is done, or we are able to hire more people (this may not happen so soon).

**Comment by stsewd** [comment]
Thanks for the kind words, hopefully we can focus on the theme soon
