### ISSUE TITLE
Line space between items in toctree list too wide

### ISSUE THREAD

**Issue by idnsunset** [readthedocs/sphinx_rtd_theme#1029]
### Problem

Line space between items in toctree list is too wide. It seems that `.rst-content .section ul li > ul` overrides `.rst-content .toctree-wrapper ul li ul` producing the 12px bottom margin and `.rst-content .section ul li>*` produces 12px top margin.

I have to set both `margin-top` and `margin-bottom` to 0 on nested `<ul>` elements in `.toctree-wrapper` to fix this.

#### Error Logs/Results

![sphinx-rtd-theme_toctree-line-space](https://user-images.githubusercontent.com/31075263/103340237-875a0f00-4abe-11eb-9d9e-f253e2a7eff4.png)

#### Expected Results

![2020-12-30-165016_209x106_scrot](https://user-images.githubusercontent.com/31075263/103340489-2b43ba80-4abf-11eb-8304-9fa393f7a69c.png)

### Environment Info

- Python Version: 3.9.1
- Sphinx Version: 3.3.1
- RTD Theme Version: 0.5.0

**Comment by nienn** [comment]
This got fixed in version `1.1` by the PR #1185 with the following code:
https://github.com/readthedocs/sphinx_rtd_theme/blob/ce74456d562b3491b75d380d7f700c317726ea63/src/sass/_theme_rst.sass#L179-L185

Also, #1202 is related to this by intentionally adding the space back for nested lists on the `.toctree-wrapper` that are outside `sections`. But it doesn't affect the margins for the `.simple` lists that was fixed by the previous code.

I'm closing this issue for now as I think the two PR above should have solved the spacing issues on the `toctree` but feel free to reopen if that is not the case.
