### ISSUE TITLE
Fonts not being retrieved

### ISSUE THREAD

**Issue by rdswift** [readthedocs/sphinx_rtd_theme#1034]
### Problem

As of version 0.5.1, the fonts are no longer copied to the output, causing the `fa-caret-down`, `fa-book`, etc. to not display correctly.

### Reproducible Project

This was first discovered on the https://github.com/rdswift/picard-docs repository because the requirements were using `sphinx-rtd-theme>=0.4.3`.  The problem was corrected when we set the requirement to `sphinx-rtd-theme==0.5.0`.

#### Error Logs/Results

![image](https://user-images.githubusercontent.com/16990904/103701246-e6a69c00-4f62-11eb-89d9-bc2b80ecd09a.png)

The `_static/fonts` directory is not being created.  Not sure, but I believe that the `_static/js` directory is also not being created.

#### Expected Results

![image](https://user-images.githubusercontent.com/16990904/103701318-08078800-4f63-11eb-9cff-968a88119793.png)

Switching back to version 0.5.0 creates and populates both the `_static/fonts` and `_static/js` directories and displays properly.

### Environment Info

- Python Version: 3.7
- Sphinx Version: 3.1.1
- RTD Theme Version: 0.5.1 (fails).  Works properly with 0.5.0

**Comment by stsewd** [comment]
Looks like this is because your custom css is expecting the fonts to be in `fonts/` https://github.com/rdswift/picard-docs/blob/master/_static/css/theme.css, but they are in `css/fonts` now. That is since 0.5.0 https://github.com/readthedocs/sphinx_rtd_theme/commit/ff594d23ff16b52f3a2d626e7c8b295f550e0de1 https://pypi.org/project/sphinx-rtd-theme/0.5.0/#files

Why is it working with 0.5.0? That's because the wheel from `0.5.0` was releaed wrong, you can see from the pypi file, that the tar file has the correct structure.

**Comment by rdswift** [comment]
Thanks for the helpful explanation.  I didn't realize that the theme.css file had also been updated.  I think I should be able to get it working now.
