### ISSUE TITLE
:download: not downloading file

### ISSUE THREAD

**Issue by drneavin** [readthedocs/sphinx_rtd_theme#1245]
### Problem

I would like to provide links to files to download on my readthedocs documents and have tried to implement this with `:download:`. The resulting html has a link with a download icon but upon clicking that link, the file is opened in the same browser window and not downloaded.

### Reproducible Project

I have tried this with sphinx v4.2.0 and sphinx_rtd_theme v1.0.0 as well as an older sphinx_rtd_theme 0.5.2

Here is an example rst code:
```rst
Solo_ has provided an :download:`example file <_download_files/solo_model.json>` that we have found to work well for most of our data.
```

And this is the html produced with the download link and button:

<img width="614" alt="Screen Shot 2021-10-09 at 1 46 19 PM" src="https://user-images.githubusercontent.com/44268007/136642302-774d0f6e-eb59-437e-a740-f9bc3c985f56.png">

And when I click on `example file`, it opens in the same window:

<img width="1434" alt="Screen Shot 2021-10-09 at 1 47 56 PM" src="https://user-images.githubusercontent.com/44268007/136642343-752c8316-0111-471a-8e9c-be57d0a01cc6.png">

I have tried in both safari and google chrome but haven't tested any other browsers

#### Expected Results

I'm hoping that the file will be downloaded directly and not opened in a new window.

### Environment Info

- Python Version: 3.9.7 (3.8.5 also tested)
- Sphinx Version: 4.2.0 (3.2.1 also tested)
- RTD Theme Version: 1.0.0 (0.5.2 also tested)

I tried to find other posts that might have identified the same issue but I haven't been able to find any yet.

Thanks for your help!

**Comment by astrojuanlu** [comment]
Hi @drneavin ! Would you clarify if this also happens with other themes, and if you have an online project that exhibits this behavior that we can look at?

**Comment by drneavin** [comment]
Hi @astrojuanlu! 

I just tried with the "Press" theme and have the same result so it must not be specific to the RTD theme. I'm pretty new to sphinx documentations so do you have any suggestions on what could be contributing to this issue or the best place to go to find help?

**Comment by astrojuanlu** [comment]
Given that this seems to happen with different teams, the culprit is probably the HTML that Sphinx generates. I just learned that it's actually possible to do with HTML only what you describe:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

Your best bet is to open this same issue on https://github.com/sphinx-doc/sphinx/issues/, providing a reproducible example (a small public repository that exhibits the undesired behavior). Feel free to ping me there!

In the meantime, I'm closing this one (we can't automatically transfer it).
