### ISSUE TITLE
background-image property in CSS not working in production

### ISSUE THREAD

**Issue by kapooramit** [readthedocs/sphinx_rtd_theme#1271]
Hi,

In a div, I have added a background image with the following property (in _theme_layout.sass):

````
background-image: URL"/_static/images/wave.png")
````

This works in dev. But in production (with a package created and installed), the URL is not working.
What works there is
````
background-image: URL("../images/wave.png")
````

What kind of change is needed to make this work? I even tried adding the following to the webpack-common.js after installing url-loader (npm install url-loader --save-dev): 
````
     {
        test: /\.(png|jpg)$/,
        loader: 'url-loader'
      },
````

**Comment by kapooramit** [comment]
I tried several things and solutions available on web but nothing helped. I gave up and hardcoded the style inline to the div. Not a good solution but working fine for now.

**Comment by nienn** [comment]
Hi @kapooramit,

Instead of editing the `_theme_layout.sass` it would be best if you added a custom CSS file in `_static/css/custom.css`.
You'll also need to add those paths to your `conf.py` file. See [Adding Custom CSS or JavaScript to Sphinx Documentation](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html).

If you still need help here, feel free to reopen the issue, and drop a link to your project if you can, as it's easier to get context.
