### ISSUE TITLE
Align bumpversion version strings

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1326]
Need to fix version string discrepancies between package.json and setup.py such that bumpversion can automatically search and replace

Subsequently open up an issue about later Node versions breaking on the package.json version scheme.

**Comment by agjohnson** [comment]
And for some background on this: it sounds like the underlying issue here is that a later Node version (18) doesn't like the PEP440 style version string in package.json. We can come back to changing this, or reconfiguring bumpversion/bumpver to output a slightly different version later. Because it differs now, bumpversion will no longer update the string in package.json.
