### ISSUE TITLE
Canonical ref does not match URL for builds that use dirhtml builder

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1406]
## Details

Upstream issue: https://github.com/sphinx-doc/sphinx/issues/9730

* Read the Docs project URL: https://packaging.python.org/en/latest/tutorials/packaging-projects/
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Config: https://github.com/pypa/packaging.python.org/blob/main/.readthedocs.yaml

## Expected Result

```
<link rel="canonical" href="[https://packaging.python.org/en/latest/tutorials/packaging-projects.html" />
```

## Actual Result

```
<link rel="canonical" href="[https://packaging.python.org/en/latest/tutorials/packaging-projects/" />
```

**Comment by benjaoming** [comment]
This is the upstream reference by the way: https://github.com/sphinx-doc/sphinx/issues/9730

**Comment by benjaoming** [comment]
This is only fixing the theme.

If we want to implement a work-around on everything hosted on RTD, we should figure out why `canonical_url` as defined here doesn't seem to be applied: https://github.com/readthedocs/readthedocs-sphinx-ext/blob/main/readthedocs_ext/_templates/readthedocs-insert.html.tmpl

**Comment by ericholscher** [comment]
I was able to fix teh canonical issue with a `HTML -> HTMLDir redirect`: https://docs.readthedocs.io/en/latest/user-defined-redirects.html#sphinx-redirects

**Comment by humitos** [comment]
The easiest fix for users here is to remove the theme configuration `canonical_url` (which is already deprecated) and use `html_baseurl` Sphinx's option instead.

Read the Docs already does this "automagically" at https://github.com/readthedocs/readthedocs.org/blob/4b2eb75bebfce04390ac3f84d1c57ef7f7126fe8/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L151-L156

Besides, I think that now Read the Docs is exposing `READTHEDOCS_CANONICAL_URL` we should use that environment variable from this theme to automatically set `html_baseurl` from this theme instead of relying on Read the Docs itself.

**Comment by benjaoming** [comment]
@humitos did something get fixed in Sphinx? The upstream issue here is that Sphinx appends `.html` to `pageurl` when it shouldn't do that for the DirHTML builder.

If we want to fix the issue quickly in the theme, I proposed #1407 as a backwards and forwards compatible workaround.

**Comment by humitos** [comment]
I'm a little lost here about how to solve this issue. What are the actionable steps to move forward from _our side_?

**Comment by ericholscher** [comment]
I think it's a Sphinx issue that we could work around, but I think Sphinx should likely fix it.

**Comment by humitos** [comment]
I checked this locally by using `html_baseurl` and building the documentation with `-b html` and `-b dirhtml`. It works as expected 💯 

However, the **deprecated** [`canonical_url`](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-canonical_url) does not work correctly with `-b dirhtml` because that's the chunk of code that has the `.html` hardcoded.

Since that option is deprecated since version 0.6.x we can call this a non-issue.

---

I perform the tests with those projects, and I see it works fine:

```
▶ curl -s https://test-builds.readthedocs.io/en/htmldir/ | grep canonical                            
    <link rel="canonical" href="https://test-builds.readthedocs.io/en/htmldir/index.html" />
...
```

```
▶ curl -s https://test-builds-disable-sphinx-manipulation.readthedocs.io/en/htmldir/ | grep canonical
    <link rel="canonical" href="https://test-builds-disable-sphinx-manipulation.readthedocs.io/en/htmldir/index.html" />
```
