### ISSUE TITLE
Can we have search result section wise in sphinx rtd theme?

### ISSUE THREAD

**Issue by rahulsrivastava1** [readthedocs/sphinx_rtd_theme#1459]
### Problem

Give details on your issue.

I have some sections in the project, and I need that if someone searches then the search page will give section-wise results.

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

#### Expected Results

Please describe how this should work properly.

### Environment Info

- Python Version:
- Sphinx Version:
- RTD Theme Version:

**Comment by benjaoming** [comment]
@rahulsrivastava1 can you write a bit more about your use-case?'

It might be solved for projects hosted on Read the Docs since it uses RTD's own server side search and client for displaying search results. This doesn't relate to sphinx-rtd-theme.

Otherwise, Sphinx has its own search function and your feature would have to be requested on Sphinx. You can read about search options here: https://www.sphinx-doc.org/en/master/usage/configuration.html

**Comment by rahulsrivastava1** [comment]
Hi @benjaoming, I have some sections in my project, and I have some pages under that section. I want that if someone to search by any keyword then the search page will appear section-wise. Right now, it is showing only the page name not section name.

**Comment by benjaoming** [comment]
@rahulsrivastava1 this works differently with projects hosted on Read the Docs, try for instance the search function here: https://docs.readthedocs.io/

**Comment by rahulsrivastava1** [comment]
@benjaoming  
I have hosted on Azure App service.

**Comment by benjaoming** [comment]
@rahulsrivastava1 you would have to use Read the Docs to have the Read the Docs search extensions available. It seems to support the feature you are asking for.

If you want a new feature for Sphinx, you should post it in the Sphinx repo: https://github.com/sphinx-doc/sphinx
