### ISSUE TITLE
Add Sphinx 7 support

### ISSUE THREAD

**Issue by MehdiChinoune** [readthedocs/sphinx_rtd_theme#1463]
### Problem

Support sphinx>=7

**Comment by benjaoming** [comment]
@Paebbels you can open an issue about Sphinx 6.1 support, sharing the error messages, and we can see if it's a real issue or not :+1:

**Comment by dyve** [comment]
```console
ERROR: Cannot install -r docs/requirements.txt (line 2) and sphinx==7.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested sphinx==7.0.1
    sphinx-rtd-theme 1.2.1 depends on sphinx<7 and >=1.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by stefaneidelloth** [comment]
Is there an alternative theme to sphinx_rtd_theme, that looks similar but has up to date dependencies?

**Comment by dyve** [comment]
> Is there an alternative theme to sphinx_rtd_theme, that looks similar but has up to date dependencies?

I switched to [Furo](https://pypi.org/project/furo/). Not visually similar, but suits my needs.

**Comment by potiuk** [comment]
Hello everyone here listening. 

As described in https://github.com/apache/airflow/issues/31963 . Our contributors (and many of them) and committers are starting to loose **hours** for debugging documentation problems in Apache Airflow because sphinx_rtd_theme holds us back from migrating to Sphinx 7. Sphinx 7 with auto-api apparently has much better error reporting facilities, and it will help us to solve the problem.

Question (I hope maintainers can answer that):

Is there a chance this issue will be solved and new release of sphinx_rtd_theme will be released soon? 

Also, is there any way we can help to make it faster? 

Seems that #1464 is there ready to be reviewed and possibly solves the problem, so not sure if there is anything else one can do ?

We are considering other options (including switching to other theme or maybe even vendoring-in sphinx_rtd_theme and applying fixes ourselves), because we are completely mind-boggled by some of the problems we have as our documentation gets richer and more comprehensive, and knowing what is thinking around releasing Sphinx 7 - compatible version of the theme.

I'd really appreciate an honest answrer - here. Note that I am not complaining - I know it's essentially Sphinx problem in version 6, and we have chosen `sphinx-rtd-theme` ourselves, nobody forced us to do it. We are also grateful for the work done so far by maintainers of sphinx_rtd_theme - as so far it saved us a lot of effort to begin with when we published our htps://airflow.apache.org site. 

But knowing what might be the expected timeline and priority for sphinx_rtd_theme maintainers might help us to make a better informed decisions.

Looking forward to hearing back from you.

**Comment by humitos** [comment]
We've released `sphinx-rtd-theme==1.3.0rc1` (https://pypi.org/project/sphinx-rtd-theme/1.3.0rc1/). You can install it via pip as following:

```
pip install sphinx-rtd-theme==1.3.0rc1
```

Please, let us know if this release works as you expected. We plan to do a final release once we get some feedback from people confirming that everything is OK. Thank you all! 🙏🏼

**Comment by potiuk** [comment]
OK. Seems it works for Airflow wihtot  big problems.

Sphinx7: http://apache-airflow-sphinx-docs.s3-website.us-east-2.amazonaws.com/docs/apache-airflow/stable/index.html

Though we have spacing/ CSS to fix (due to docutils upgrade apparently).

Sphinx 5: https://airflow.apache.org/docs/

**Comment by Tenzer** [comment]
The RC works well for us and allowed us to upgrade to Sphinx 7.

**Comment by psss** [comment]
Verified in teemtee/tmt/pull/2249 that docs [building works](https://readthedocs.org/projects/tmt/builds/21542224/) fine again with `sphinx-rtd-theme==1.3.0rc1`. When do you plan to do the final release? Will it be there soon or is it still worth applying the hotfix? Thanks.

**Comment by potiuk** [comment]
> We'll probably give this a little more time to simmer and receive some more feedback. But I suspect we won't hit any major blocking issues besides issues around lack of docutils 0.19+ support. Perhaps later this week or next Tues we can aim for the full release.

Cool. That would be great. We have some high hopes because there seem to be improvements (apparently - looking at Github Issues) that Sphinx 7 has when it comes to error messages. We have rather extensive documentation coming from various sources (docstring/rst files/jinja pre-processed .rst files and so on) and it's often trial-and-error for some of the changes from our users to figure out what's wrong with their docs (especially about empty lines and indentations). Apparently Sphinx 7 has at least some of it improved. I remember loosing hours on trying to bi-sect the change and narrow it down to some parts to see which one caused problems with Sphinx we were limited to.

I even kept on saying to our contributtors " Well It's a known fact that Sphinx speak riddles - you just need to figure it out" 😄
