### ISSUE TITLE
last_updated gone in footer ?

### ISSUE THREAD

**Issue by Carreau** [readthedocs/sphinx_rtd_theme#238]
#208 seem to have made `last_updated` in footers visible only in last resort.

Can  it be added **in addition** to the revision number as revision number are nice for developers, but pretty useless for user that just want to know how old docs are ?

If so I can make a PR.

**Comment by agjohnson** [comment]
We had plans to link the hash to the RTD build object, or it could link back to the github commit via the hash -- maybe that would be better? It would give the closest approximation of the time the file was edited, and not just the time the file was generated on RTD.

If we can give a short hash from RTD (on the roadmap, I don't think there's a ticket), I don't see much of a problem in appending the date as well. Less redundant info down there the better, I suppose. It got bumped orignally because there was too much going on at the bottom of the page.

We could also use a configuration option here, though I don't know if that would be polluting our configuration option namespace or not.

**Comment by Carreau** [comment]
> or it could link back to the github commit via the hash

If you have the commit hash, you could have the commit date, no ?

And you could have a date, which link to the commit.
That would make things compact, easy to read, and with access to more info if needed. 

> It got bumped orignally because there was too much going on at the bottom of the page.

Yep, I understand. 

I basically like to know when I land on a page if the doc build is from today, last  week, last month, or last year, so that I can get an idea of wether the docs are autobuilding/maintained.

I suppose you know about it, but a nice way to format date is [momentjs](http://momentjs.com/).

Thanks !

**Comment by ava-dylang** [comment]
Are 'last updated dates' ever coming back to the stock theme? I'm not quite sure how I can add this in without making a fork of the module. Is there a simple way to get this back?

**Comment by Moini** [comment]
I like the suggestion by @Carreau, it would make it a lot easier for contributors to documentation to see if their changes have taken effect, and for users to see how old the docs are. The commit hash is not useful for this at all. If the date can then be linked to the commit, this would be perfect, and eliminate the need (or longing) for a custom theme for many.

**Comment by thomas-nilsson-irfu** [comment]
Is there any progress on this issue at all or has is completely died out?

It should not be too difficult to allow for generated documentation to simply include the dates **and** the commit hash (if the author would like for it to be so), or? Instead of forcing the author to choose one and only one of these to show.

This could possibly be set with some simple if-statement, similar to how the `copyright` is handled:
https://github.com/readthedocs/sphinx_rtd_theme/blob/f237820d2cc84cb9a111fd67a3f0b162b03ba3ad/sphinx_rtd_theme/footer.html#L17-L23

**Comment by Blendify** [comment]
This works simply add "html_last_updated_fmt = '%m/%d/%Y'" to your conf.py

**Comment by 1138-4EB** [comment]
@Blendify, this issue is about showing the date **AND** the commit hash:

> Can it be added **in addition** to the revision number

> include the dates **and** the commit hash (...) Instead of forcing the author to choose one and only one of these to show.

**Comment by mgeier** [comment]
@Blendify 

> This works simply add `html_last_updated_fmt = '%m/%d/%Y'` to your conf.py

It doesn't work on https://readthedocs.org/, though, because they forcefully set the `html_context['commit']` value.

I've just created a Sphinx extension that takes the `last_updated` information from Git (individually for each source file): https://github.com/mgeier/sphinx-last-updated-by-git

Sadly, it doesn't work on RTD because of this issue.

I think it would be reasonable (as already suggested multiple times above) to show *both* the commit hash and the last changed date.

**Comment by mgeier** [comment]
Any news on this?
What about a design decision?

The solution is only a click away: #897

**Comment by agjohnson** [comment]
Noted at https://github.com/readthedocs/sphinx_rtd_theme/pull/897#issuecomment-661422147 but the main issue that RTD will have with using `last_updated` is that we rebuild every file every build. `last_updated` will always be the date of the last project build, for every file.

So, for a design decision, I think a link to the commit is (currently) more truthy than always showing `last_updated`, but would 100% love to have the last commit date of the source file if we had it available.

**Comment by mgeier** [comment]
Noted at https://github.com/readthedocs/sphinx_rtd_theme/pull/897#issuecomment-661741952, displaying the "last updated" data is an *opt-in* mechanism.
