### ISSUE TITLE
Allow to collapse sidebar even on Desktop.

### ISSUE THREAD

**Issue by Carreau** [readthedocs/sphinx_rtd_theme#336]
The logic seem to be here already on mobile. I would suggest to extend it to be collapsible on Desktop as well, in order to have the option to get distraction-free reading.

**Comment by MarjaE2** [comment]
I don't know if there's a way to hide it yet, but I can't find it, and I have a migraine from the accursed sidebar.

**Comment by RadixSeven** [comment]
Because of RSI, I use an eye-tracker and foot mouse buttons to minimize hand use. The eye-tracker only works with a single-monitor setup. Even though I have the widest monitor that works with the eye tracker, the sidebar makes the main text extremely narrow when I have the documentation in a browser in one window at the same time as an IDE in another window.

**Comment by RadixSeven** [comment]
My current workaround is to go into responsive design mode. (CTRL+ SHIFT + M on Firefox) I set the resolution to 768x847. The "responsive design mode" toggle toggles the sidebar.

**Comment by humitos** [comment]
Closing as dup of #987 that has more discussion about this.
