### ISSUE TITLE
Add copy-to-clipboard button to code blocks

### ISSUE THREAD

**Issue by ThiefMaster** [readthedocs/sphinx_rtd_theme#429]
Unlike [2 years ago](https://github.com/rtfd/sphinx_rtd_theme/pull/257) there is now decent support to copy something to the clipboard without using Flash: https://clipboardjs.com/ (it can also be done with vanilla JS, but that library is quite nice for it)

Especially when having an install guide in your docs that contains shell commands it would be nice if people could easily copy them to the clipboard. Same if there's a code snippet in a quickstart guide people should paste in a REPL or use it as a starting point to write their own code.

**Comment by Blendify** [comment]
This is something that would be nice to support but I think the only way to do this is through an extension to the html writer. So not sure how we want to add this. My personal preference is that we write a small extension and include it as a

**Comment by choldgraf** [comment]
Another option would be for somebody to tutorialize this on a one-off basis. If it'll be some time before an extension etc gets written, people could still build this into their pre-existing builds with some nicely-written instructions

**Comment by choldgraf** [comment]
Update: I implemented this as a super lightweight sphinx extension: https://github.com/choldgraf/sphinx-copybutton

Perhaps @Blendify @ThiefMaster or @jessetan could give it a look and LMK what you think!

**Comment by jessetan** [comment]
Great initiative!
I have some comments that may not be all applicable depending on the intended use, I'll leave it to you to consider how valid these are.

- I like the UX (hover, fade animation), but I would remove the selection of the code block after copying. Instead some pop up or color change of the icon can be used to indicate text was copied instead of the current default browser click outline
- Have you considered what this will look like for different background colors? (a site might use a different pygments theme)
- Bundle the CSS and JS files with the generated documentation during the build instead of linking to the files on GitHub. This will make it work for offline documentation and can be faster because it does not require a request to an external server
- Bundle the clippy svg with your extension
- Use existing ids instead of setting your own id on a code block if there is already one present, you might break other functionality that depends  on this exact id
- The class `.btn` that clipboard.js attaches to is a bit generic, something more unique would be better
- All logic in `addCopyButtonToCode()` can be moved to Python code in your extension to reduce the load time for the end user (no need to wait for page load and no need to create elements in JS). The only JS you really need is including clipboard.js and passing it the selector of your copy buttons
- Make the alt text of the copy button configurable in your extension options to support l10n
- Your extension depends on jQuery. Sphinx also depends on this, but this could change. Since the extension code is so small, you could do this in vanilla JS

The size and implications of this list may be intimidating, but it can make a difference between being suitable for your own uses vs suitable for a wide variety of users. Only you can decide how much effort you can put into this. Again, kudos for creating an extension.
Further discussion might be better suited for issues in the repo of your extension

**Comment by choldgraf** [comment]
another quick update on this: sphinx-copybutton is now a lot more lightweight, following several of the suggestions from @jessetan above (thanks for those). Some of the configuration options are still missing (largely because I can't figure out how to grab configuration from the `conf.py` file), but I think it's a much more generically-usable extension now!

Thoughts, PRs, issues, etc more than welcome!

https://github.com/choldgraf/sphinx-copybutton

**Comment by Blendify** [comment]
@agjohnson what are your thoughts on enabling by default and making sphinx-copybutton a dependency of the theme?

**Comment by agjohnson** [comment]
Hrm, not sure. I find the extension very useful on our docs, but it feels like an option to leave up to the author. We have this extension on our list of extensions to promote more, which is probably where I'd vote to start with this feature for now. If anyone felt strongly about making this the default, we could save a few file requests, but I do prefer having an extension that is usable outside this theme. I'll close this for now, as I don't see us adding this natively to the theme
