### ISSUE TITLE
Field list display different in Sphinx 2

### ISSUE THREAD

**Issue by jonashaag** [readthedocs/sphinx_rtd_theme#855]
Sphinx 1:
![Screenshot 2019-11-06 at 15 30 45](https://user-images.githubusercontent.com/175722/68306782-78d6ba00-00aa-11ea-97fb-2ca24a9510ab.png)

Sphinx 2:
![Screenshot 2019-11-06 at 15 30 40](https://user-images.githubusercontent.com/175722/68306803-82f8b880-00aa-11ea-96d1-37a1a197e497.png)

This is *not* fixed with #838

**Comment by agjohnson** [comment]
We likely won't aim for parity here initially. The styles with the html4 writer use a table display. With the html5 writer, the output is a definition list. Because there is no wrapper element, such as a  `<tr>` or `<div>`, in a definition list, the solution to this is going to be doing some gross stuff with flex.

**Comment by davidelbaze** [comment]
In my opinion, the render with Sphinx 1 is much more concise and nice to read.

**Comment by agjohnson** [comment]
Yup, I agree. There's a lot of undue aversion to tables in modern HTML, but unfortunately, this seems like it was pretty obvious case for tables to begin with.

**Comment by cjw296** [comment]
@agjohnson - we're now on Sphinx 3, right?

I'm not sure I follow why this issue is marked as done, here's 0.4.3:
https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html#field-list

Here's master:
https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/lists_tables.html#field-list

What am I missing?

**Comment by hugobuddel** [comment]
The master version of the fieldlist is about twice as high as in 0.4.3. With more than 1200 pixels it doesn't even fit on my laptop screen. Having to scroll up and down makes the information significantly harder to interpret, especially when comparing multiple of such field sets next to each other.

Arguably option lists (#801) look better, but field lists certainly do not.
