### ISSUE TITLE
Can we get a new release of master branch that addresses #825

### ISSUE THREAD

**Issue by pallavg** [readthedocs/sphinx_rtd_theme#886]
### Problem

Facing the same issue in #825. Would it be possible to release the latest master code as a new version. I believe that fixes this problem. Right now, the solution is for me to downgrade to use v0.3.1. Thank you.

### Reproducible Project

N/A See #825 

#### Error Logs/Results

N/A. See #825 

#### Expected Results

python manage.py collectstatic should not fail.

### Environment Info

- Python Version: 3.7
- Sphinx Version: 2.4.4
- RTD Theme Version: 0.4.3

**Comment by Alexdara** [comment]
Maybe you can try this
`pip install -e git+https://github.com/readthedocs/sphinx_rtd_theme.git@master#egg=sphinx-rtd-theme`
to use the master branch.

**Comment by sylvestre** [comment]
Yeah, it would be great
172 commits to master since the last release

**Comment by polyzen** [comment]
AFAIK a release has been blocked on Sphinx 2 compatibility:
https://github.com/readthedocs/sphinx_rtd_theme/projects/1

**Comment by lazka** [comment]
I'd also like to see a new release to fix all the FOUC problems with Firefox.

**Comment by MatinF** [comment]
> I'd also like to see a new release to fix all the FOUC problems with Firefox.

Same here :-)

**Comment by jack1142** [comment]
Sphinx 3.0 has already been released and `master` branch already contains fixes for things that were removed in it. Is it really necessary to wait until full Sphinx 2 compatibility is provided? I'm sure a lot of projects use this theme with Sphinx 2.0+ already and in my opinion, making a release with *only* some of the compatibility fixes is better than not making the release at all and waiting until full support is ready. Most issues don't exist on old HTML 4 writer and it isn't going away any time soon so until the project is ready to provide full support for the new writer, it would be awesome if the other stuff that contributors have committed since last release were finally released.
Unless you really are close to the next release (and from the "Sphinx 2" project, it doesn't seem this way), making a release with what you have already seems like a good idea.

**Comment by davidelbaze** [comment]
I totally agree with the previous comment. Now that Sphinx 3 is released, we should make a step to it.

**Comment by agjohnson** [comment]
New release is waiting on fixes for html5 writer in #838. A 0.5rc1 release should be out next week if we can finalize that PR next week. Fixes for anything not related to html5 writer compatibility will come in a further release

**Comment by agjohnson** [comment]
Also, to clarify on the original report here, we won't be catering to installation through a GitHub URL in future releases. We removed this installation method from our guide a while ago and will be moving towards releasing more frequently now that we have this heavy release out of the way.

More frequent releases hopefully will assist users from needed to install from our repository.

If you are currently pointing towards the GitHub URL to get the latest, you should be moving to the PyPI release instead. Temporarily, the font issue described might (?) go away, however we will not be storing compiled assets in the repository once we figure out a suitable migration path for users.

More discussion here:
https://github.com/readthedocs/sphinx_rtd_theme/issues/379
