### ISSUE TITLE
Pip installed theme does not translate UI

### ISSUE THREAD

**Issue by allcaps** [readthedocs/sphinx_rtd_theme#888]
### Problem

When I set `language = "nl"` in conf.py Sphinx RTD Theme user interface doesn't switch language.

When I disable the theme, the default Sphinx theme _is_ translated into Dutch.

### Reproducible Project

`pip install sphinx-rtd-theme`

In conf.py
```
language = "nl"
html_theme = "sphinx_rtd_theme"  # enable/disable and make html
```
#### Expected Results

I expect the UI to be translated to Dutch.
- `Search` to be translated to Dutch `Zoek` or `Zoeken`.
- `Previous/Next` => `Vorige/Volgende`

### Debugging

In site-packages the sphinx_rtd_theme package does not have a locale directory.

The repo does have it:
https://github.com/readthedocs/sphinx_rtd_theme/tree/master/sphinx_rtd_theme/locale/nl/LC_MESSAGES

When I install from github, it works.
`$ pip install -e git+git@github.com:readthedocs/sphinx_rtd_theme.git#egg=sphinx_rtd_theme`

The strange thing is that locals are included in the manifest.
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/MANIFEST.in

Is setup.py package_data incomplete?
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/setup.py#L103

### Environment Info
- Python Version: Python 3.7.3
- Sphinx Version: Running Sphinx v2.4.4
- RTD Theme Version: sphinx-rtd-theme==0.4.3

**Comment by mondeja** [comment]
The installation script `setup.py` is not incomplete, simply the maintainer of the distribution tarball for Pypi is not including the locales directory for some reason.

When you install the library using `sphinx-rtd-theme`, pip retrieves [this file](https://files.pythonhosted.org/packages/ed/73/7e550d6e4cf9f78a0e0b60b9d93dba295389c3d271c034bf2ea3463a79f9/sphinx_rtd_theme-0.4.3.tar.gz) as you can see [here](https://pypi.org/project/sphinx-rtd-theme/#files).

You can test it following the next steps:

1. Change the name of the package in `setup.py` from `"sphinx_rtd_theme"` to `"allcaps_sphinx_rtd_theme"`.
2. Run `python3 setup.py sdist bdist_wheel` to generate source code tarball.
3. Install twine with `pip install twine`.
4. Upload the package to testing mirror of Pypi: `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`
5. Install the package with `python3 -m pip install --index-url https://test.pypi.org/simple/ allcaps_sphinx_rtd_theme` and you will see in your virtual evironment the package `sphinx_rtd_theme` with the locales directory included.

[This](https://test-files.pythonhosted.org/packages/38/d9/6c5b5508c6eff6159b071b8dc36c1b6a7d5b71cd23b382485adb4d7fedd9/mondeja_sphinx_rtd_theme-0.4.3.dev0.tar.gz) is the version that I've uploaded and you can see that locales directory is included.

As I can imagine, they don't include that because there are too few developers using localization and this might increase the distribution file size, and the few developers that include them are using the github development branch.

All of this are only my assumptions after seeing that this behavior is repeated in other libraries, but this makes sense because usually localization files are not updated so fast as code grows.

It would be nice that we could include a `[locale]` extra marker that indicate that the library needs to include locales (maybe distributing locales in another Python package?). For now, install it from Github.

**Comment by allcaps** [comment]
Thank you @mondeja for your nice response. 

I now install with this in requirements.txt to pin to an exact commit.

`git+https://github.com/readthedocs/sphinx_rtd_theme.git@ca015a57042713ebd7f39563cdb01fab5b604051#egg sphinx_rtd_theme`

**Comment by Blendify** [comment]
I believe this issue just needs the new version of the theme released to pip?

We are working on it and hope to get a release out soon.

**Comment by allcaps** [comment]
Ah, thats probably right. I didn't realise that 4.0.3 did not have locale at all.

**Comment by agjohnson** [comment]
Correct. No locale updates since the last release. 0.5rc1 release will have the new translation updates. PR for updates is #909.

Closing this as a duplicatte
