### ISSUE TITLE
how to overwrite index.html and set logo's link to index.html

### ISSUE THREAD

**Issue by Lijiaoa** [readthedocs/sphinx_rtd_theme#926]
### Problem

I rewrite a page named `custom.html` in template, and how to set `when I click the logo, page link to ../custom.html rather than index.html ?`

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

#### Expected Results

Please describe how this should work properly.

### Environment Info

- Python Version:
- Sphinx Version:
- RTD Theme Version:

**Comment by agjohnson** [comment]
We don't have a specific block around just the link or logo link, so you'd have to override the entire `sidebartitle` block:
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/layout.html#L116-L146

We don't have any specific configuration for this otherwise. If you aren't familiar with Sphinx templating, their docs have some resources, or you can look at some of the existing themes that extend the `basic` theme for an idea of how to accomplish this. The templating docs do cover extending templates, which is what you'd be looking to do to alter this link.
