### ISSUE TITLE
Permalink characters broken

### ISSUE THREAD

**Issue by seanh** [readthedocs/sphinx_rtd_theme#98]
![screenshot from 2014-02-06 15 54 50](https://f.cloud.github.com/assets/22498/2099658/ea740d9a-8f3e-11e3-8a99-eba1b677734e.png)

**Comment by astrojuanlu** [comment]
Getting hit by this with Sphinx 5.3.0 and sphinx_rtd_theme 1.2.0... whatever the value of `html_permalinks_icon` (new in Sphinx 3.5 https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_permalinks_icon, released 7 years after this bug was closed), it gets replaced by `\uf0c1`, unicode for https://fontawesome.com/icons/link

https://github.com/readthedocs/sphinx_rtd_theme/blob/ee64d37ac95fcfe7a1e53d7ab72e09704606261e/sphinx_rtd_theme/__init__.py#L72-L76

(I know it's probably not _exactly_ the same issue, but leaving the comment here just in case other people arrive from search engines)

**Comment by benjaoming** [comment]
@astrojuanlu I used to check if the theme was updated to =>1.1 by verifying that the permalink icon looks correct :)

This is correct:

![image](https://user-images.githubusercontent.com/374612/231159167-ea945cff-b597-46a7-a254-b36d8f782c23.png)

If you are not seeing this icon, could it be that Font Awesome is missing?

**Comment by astrojuanlu** [comment]
We're not, but regardless, we want to keep using ¶. This did the trick for us:

```python
def _override_permalinks_icon(app):
    # https://github.com/readthedocs/sphinx_rtd_theme/issues/98#issuecomment-1503211439
    app.config.html_permalinks_icon = "¶"


def setup(app):
    app.connect("builder-inited", _override_permalinks_icon)
```
